const ADminCreateAUser = {"metadata":{"allOf":[{"type":"object","properties":{"email":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Email of user to create"},"first_name":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"First name of user to create"},"last_name":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Last name of user to create"},"user_mode":{"type":"string","default":"normal","$schema":"http://json-schema.org/draft-04/schema#","description":"User mode of the user to create, must be one of \"benefactor\", \"bot\", \"normal\", \"observer\", or \"receiver\""},"budget_boost":{"type":"number","$schema":"http://json-schema.org/draft-04/schema#","description":"Amount to supplement user's monthly bonus by"},"external_unique_id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Unique identifier from a third party system"},"time_zone":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Time zone of the user to create of the format \"Country/City\""},"country":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"The two letter country code of the user to create, eg \"US\" for the United States"},"send_invite":{"type":"boolean","$schema":"http://json-schema.org/draft-04/schema#","description":"Send an invitation email?"},"hired_on":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"The date on which the user was hired"},"date_of_birth":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"The user's birthday. We will strip the year for privacy."},"manager_email":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"The email address of the user's manager"}},"required":["email","first_name","last_name"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ADminDeactivateAUser = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ADminUpdateACompany = {"body":{"type":"object","properties":{"name":{"type":"string","examples":["Initech"]},"custom_user_properties":{"type":"array","items":{"type":"string","examples":["department"]}}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ADminUpdateAUser = {"body":{"type":"object","properties":{"email":{"type":"string","examples":["blumbergh@initech.com"]},"first_name":{"type":"string","examples":["Bill"]},"last_name":{"type":"string","examples":["Lumbergh"]},"user_mode":{"type":"string","examples":["normal"]},"budget_boost":{"type":"number"},"external_unique_id":{"type":"string","examples":["foo"]},"custom_properties":{"type":"object","properties":{}},"time_zone":{"type":"string","examples":["America/Los_Angeles"]},"country":{"type":"string","examples":["US"]},"manager_email":{"type":"string","examples":["bossbergh@initech.com"]}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Achievements = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ActivateOrDeactivateAUser = {"body":{"type":"object","properties":{"active":{"type":"boolean"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"204":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ApproveCustomRewardRedemptions = {"body":{"type":"object","properties":{"ids":{"type":"array","items":{"type":"string","examples":["67f6a95dbf8c7f0ee520d902"]}}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","properties":{"success":{"type":"boolean"},"result":{"type":"object","properties":{"success":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"user_id":{"type":"string"},"user_email":{"type":"string"},"name":{"type":"string"},"amount_in_points":{"type":"number"},"categories":{"type":"array","items":{"type":"string"}},"fulfillment_partner":{"type":"string"},"color":{"type":"string"},"size":{"type":"string"},"shipping_address":{"type":"string"},"state":{"type":"string"},"claim_date":{"type":"string"},"approved_date":{"type":"string"},"fulfilled_date":{"type":"string"}}}},"errors":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"}}}}}}},"$schema":"http://json-schema.org/draft-04/schema#"},"422":{"type":"object","properties":{"success":{"type":"boolean"},"result":{"type":"object","properties":{"errors":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"message":{"type":"string"}}}}}}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Autocomplete = {"metadata":{"allOf":[{"type":"object","properties":{"search":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"}},"required":["search"]}]},"response":{"200":{"type":"object","properties":{}},"400":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Bonuses = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]},{"type":"object","properties":{"limit":{"type":"number","default":20,"$schema":"http://json-schema.org/draft-04/schema#","description":"Number of bonuses to retrieve (min: 1, max: 100)"},"skip":{"type":"number","$schema":"http://json-schema.org/draft-04/schema#","description":"Number of bonuses to skip (for pagination, min: 0)"},"start_time":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `2015-10-28T21:26:50Z`"},"end_time":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `2015-10-28T21:26:50Z`"},"hashtag":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `%23teamwork`"},"include_children":{"type":"boolean","default":"false","$schema":"http://json-schema.org/draft-04/schema#"},"role":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"'giver' or 'receiver'"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CancelApiKey = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the API key to destroy"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"401":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CreateABonus = {"body":{"type":"object","required":["reason"],"properties":{"giver_email":{"type":"string","format":"email","examples":["blumbergh@initech.com"]},"reason":{"type":"string","examples":["+10 @george and @john for #excellence with that customer, check out the email chain &lucy #service"]},"parent_bonus_id":{"type":"string","examples":["24abcdef1234567890abcdef"]}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CreateARedemption = {"body":{"type":"object","properties":{"catalog_item_id":{"type":"string","description":"ID of the item in the Bonusly reward catalog"}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CreateAUser = {"body":{"type":"object","properties":{"name":{"type":"object","properties":{"givenName":{"type":"string","examples":["Alan"]},"familyName":{"type":"string","examples":["Turing"]}}},"userName":{"type":"string","examples":["alpal@bonus.ly"]},"urn:scim:schemas:extension:enterprise:1.0":{"type":"object","properties":{"department":{"type":"string","examples":["Computational Science"]}}},"urn:scim:schemas:extension:bonusly:1.0:User":{"type":"object","properties":{"location":{"type":"string","examples":["Bletchley Park"]},"hired_on":{"type":"string","format":"YYYY-MM-DD","examples":["2023-11-27"]},"date_of_birth":{"type":"string","format":"YYYY-MM-DD","examples":["1990-09-03"]}}}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CreateApiKey = {"metadata":{"allOf":[{"type":"object","properties":{"label":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Label explaining the use case of this API key."},"read_only":{"type":"boolean","$schema":"http://json-schema.org/draft-04/schema#","description":"If provided as `true`, the created API key will only be able to read data from the API (not create/update/destroy)."},"user_id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Admins can specify a different user for which to create the API key."}},"required":["label","read_only"]}]},"response":{"201":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"401":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const CreateWebhook = {"body":{"type":"object","properties":{"url":{"type":"string","examples":["https://foobarbaz.com"]},"event_types":{"type":"array","items":{"type":"string","examples":["bonus.created"]}}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const DeleteABonus = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the bonus"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const FulfillCustomRewardRedemptions = {"body":{"type":"object","properties":{"ids":{"type":"array","items":{"type":"string","examples":["67f6a95dbf8c7f0ee520d902"]}}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","properties":{"success":{"type":"boolean"},"result":{"type":"object","properties":{"success":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"user_id":{"type":"string"},"user_email":{"type":"string"},"name":{"type":"string"},"amount_in_points":{"type":"number"},"categories":{"type":"array","items":{"type":"string"}},"fulfillment_partner":{"type":"string"},"color":{"type":"string"},"size":{"type":"string"},"shipping_address":{"type":"string"},"state":{"type":"string"},"claim_date":{"type":"string"},"approved_date":{"type":"string"},"fulfilled_date":{"type":"string"}}}},"errors":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"message":{"type":"string"}}}}}}},"$schema":"http://json-schema.org/draft-04/schema#"},"422":{"type":"object","properties":{"success":{"type":"boolean"},"result":{"type":"object","properties":{"errors":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"message":{"type":"string"}}}}}}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMetadataAboutTheBonuslyScimapi = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1AnalyticsWords = {"metadata":{"allOf":[{"type":"object","properties":{"placeholder":{"type":"boolean","$schema":"http://json-schema.org/draft-04/schema#","description":"For testing purposes setting this paramter to `true` will return a set of fake words data."}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"449":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerParticipation = {"metadata":{"allOf":[{"type":"object","properties":{"time_segment":{"type":"string","default":"month","enum":["month","week"],"examples":["month"],"$schema":"http://json-schema.org/draft-04/schema#","description":"Period to segment the data"}},"required":[]},{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"401":{"type":"object","properties":{"success":{"type":"boolean","examples":[false]},"message":{"type":"string","examples":["Bad or missing access token"]}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionAddons = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionBonusesReceived = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionCompareRates = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionHashtagsAll = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","properties":{"body":{"type":"object","properties":{"categories":{"type":"array","description":"Months in data set","examples":["Mar '22, Apr '22"],"items":{}},"series":{"type":"object","properties":{"company_value":{"type":"boolean"},"data":{"type":"array"},"name":{"type":"string"}}}}}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionHashtagsCoreValue = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionPointsReceived = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionRates = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetV1DataLayerRecognitionUserCount = {"metadata":{"allOf":[{"type":"object","properties":{"Content-type":{"type":"string","enum":["text/csv","application/json"],"$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Leaderboards = {"metadata":{"allOf":[{"type":"object","properties":{"direction":{"type":"string","default":"received","enum":["received","given"],"$schema":"http://json-schema.org/draft-04/schema#","description":"Specifies whether to rank users based on number of bonuses given, or number of bonuses received."},"hashtag":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"If specified, only bonuses whose most relevant hashtag matches the given hashtag will be returned."},"team":{"type":"string","default":"entire-company","$schema":"http://json-schema.org/draft-04/schema#","description":"Restricts users returned to those on a particular team, or in a particular part of your company. This argument may be either the id of a manager, eg. '59350a4af9f4ff084f7a0df6', or a set of custom properties in a JSON object, eg. '{\"department\":\"engineering\"}'."},"start_date":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"If specified, only bonuses given on or after this date will be considered. Defaults to 30 days before the date of your query. Date format must be a two digit date followed by a space, a three letter month followed by a space, and a four digit year, eg. \"19+Mar+2017\"."},"end_date":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"If specified, only bonuses given on or before this date will be considered. Defaults to the date of your query. Date format must be a two digit date followed by a space, a three letter month followed by a space, and a four digit year, eg. \"19+Mar+2017\"."}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"449":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListAchievements = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListApiKeys = {"metadata":{"allOf":[{"type":"object","properties":{"user_id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"If using an admin access_token, you can see other user's API keys (within your company)."}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListBonuses = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"number","default":20,"$schema":"http://json-schema.org/draft-04/schema#","description":"Number of bonuses to retrieve (min: 1, max: 100)"},"skip":{"type":"number","$schema":"http://json-schema.org/draft-04/schema#","description":"Number of bonuses to skip (for pagination, min: 0)"},"start_time":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `2015-10-28T21:26:50Z`"},"end_time":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `2015-10-28T21:26:50Z`"},"giver_email":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"receiver_email":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#"},"user_email":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Retrieve bonuses that have either giver or receiver with this email"},"hashtag":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `%23teamwork`"},"include_children":{"type":"boolean","default":"false","$schema":"http://json-schema.org/draft-04/schema#"},"show_private_bonuses":{"type":"boolean","$schema":"http://json-schema.org/draft-04/schema#","description":"Include private bonuses, only works for admins."}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListCustomRewardsRedemptions = {"metadata":{"allOf":[{"type":"object","properties":{"state":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Filter by state. Example: `new` or `approved` or `fulfilled`"},"fulfillment_partner":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Filter by fulfillment partner. Example: `Bonusly` or `Virtual Reward Center`"}},"required":[]}]},"response":{"200":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"user_id":{"type":"string"},"user_email":{"type":"string"},"name":{"type":"string"},"amount_in_points":{"type":"number"},"categories":{"type":"array","items":{"type":"string"}},"fulfillment_partner":{"type":"string"},"color":{"type":"string"},"size":{"type":"string"},"shipping_address":{"type":"string"},"state":{"type":"string"},"claim_date":{"type":"string"},"approved_date":{"type":"string"},"fulfilled_date":{"type":"string"},"errors":{"type":"array","items":{"type":"object","properties":{"id":{"type":"string"},"message":{"type":"string"}}}}}},"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","properties":{"success":{"type":"boolean"},"message":{"type":"string"}},"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListRedemptions = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"number","default":100,"$schema":"http://json-schema.org/draft-04/schema#","description":"Number of users to retrieve (min: 1, max: 100)"},"skip":{"type":"number","$schema":"http://json-schema.org/draft-04/schema#","description":"Number of users to skip (for pagination, min: 0)"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListRewards = {"metadata":{"allOf":[{"type":"object","properties":{"catalog_country":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `US`"},"request_country":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `US`"},"personalize_for":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"User id"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListTheScimResourceTypesSupportedByBonusly = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListTheScimSchemasSupportedByBonusly = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const ListUsers = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}},"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"number","default":20,"$schema":"http://json-schema.org/draft-04/schema#","description":"Number of users to retrieve (min: 1, max: 100)"},"skip":{"type":"number","$schema":"http://json-schema.org/draft-04/schema#","description":"Number of users to skip (for pagination, min: 0)"},"email":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: `blumbergh%40initech.com`"},"externalId":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: 'abc123'"},"sort":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Options: created_at, last_active_at, display_name, first_name, last_name, email, country, time_zone. Default order is 'Ascending', prefix an option with '-' to specify 'Descending'"},"include_archived":{"type":"boolean","default":"false","$schema":"http://json-schema.org/draft-04/schema#","description":"Include archived/deactivated users"},"show_financial_data":{"type":"boolean","$schema":"http://json-schema.org/draft-04/schema#","description":"Whether or not to include financial data (giving balance, etc.) (admin only)"},"user_mode":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"comma separated list of user_modes (valid user modes are normal, observer, receiver, benefactor, bot)"}},"required":[]}]}} as const
;
const ListWebhooks = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Me = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Redemptions = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]},{"type":"object","properties":{"limit":{"type":"number","default":20,"$schema":"http://json-schema.org/draft-04/schema#","description":"Number of bonuses to retrieve (min: 1, max: 100)"},"skip":{"type":"number","$schema":"http://json-schema.org/draft-04/schema#","description":"Number of bonuses to skip (for pagination, min: 0)"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RemoveWebhook = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the webhook"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RetrieveABonus = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the bonus"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RetrieveACompany = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RetrieveARedemption = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the redemption"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RetrieveAReward = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the reward"}},"required":["id"]},{"type":"object","properties":{"request_country":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Example: US"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const RetrieveAUser = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const Trends = {"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"449":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const UpdateABonus = {"body":{"type":"object","properties":{"reason":{"type":"string","examples":["+10 @george and @john for #excellence with that customer, check out the email chain &lucy #service"]}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the bonus"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const UpdateAnExistingUser = {"body":{"type":"object","properties":{"urn:scim:schemas:extension:enterprise:1.0":{"type":"object","properties":{"department":{"type":"string","examples":["Cryptography"]}}}},"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const UpdateWebhook = {"metadata":{"allOf":[{"type":"object","properties":{"id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the webhook"}},"required":["id"]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const XMlListBonuses = {"metadata":{"allOf":[{"type":"object","properties":{"navori":{"type":"boolean","default":"false","$schema":"http://json-schema.org/draft-04/schema#","description":"Request XML response with formatting for Navori"}},"required":[]}]},"response":{"200":{"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
export { ADminCreateAUser, ADminDeactivateAUser, ADminUpdateACompany, ADminUpdateAUser, Achievements, ActivateOrDeactivateAUser, ApproveCustomRewardRedemptions, Autocomplete, Bonuses, CancelApiKey, CreateABonus, CreateARedemption, CreateAUser, CreateApiKey, CreateWebhook, DeleteABonus, FulfillCustomRewardRedemptions, GetMetadataAboutTheBonuslyScimapi, GetV1AnalyticsWords, GetV1DataLayerParticipation, GetV1DataLayerRecognitionAddons, GetV1DataLayerRecognitionBonusesReceived, GetV1DataLayerRecognitionCompareRates, GetV1DataLayerRecognitionHashtagsAll, GetV1DataLayerRecognitionHashtagsCoreValue, GetV1DataLayerRecognitionPointsReceived, GetV1DataLayerRecognitionRates, GetV1DataLayerRecognitionUserCount, Leaderboards, ListAchievements, ListApiKeys, ListBonuses, ListCustomRewardsRedemptions, ListRedemptions, ListRewards, ListTheScimResourceTypesSupportedByBonusly, ListTheScimSchemasSupportedByBonusly, ListUsers, ListWebhooks, Me, Redemptions, RemoveWebhook, RetrieveABonus, RetrieveACompany, RetrieveARedemption, RetrieveAReward, RetrieveAUser, Trends, UpdateABonus, UpdateAnExistingUser, UpdateWebhook, XMlListBonuses }
